# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-string-match-scorer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bodaniel Jeanes"]
  s.date = %q{2009-12-10}
  s.description = %q{Flex matching short abbreviations against longer strings is a boon in productivity for typists. Applications like Quicksilver, LaunchBar, and Launchy have made this method of keyboard entry a popular one.}
  s.email = %q{me@bjeanes.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/string_scorer.rb",
     "lib/string_scorer/scorer.rb",
     "lib/string_scorer/scorers/liquidmetal.rb",
     "lib/string_scorer/scorers/quicksilver.rb",
     "lib/string_scorer/string_ext.rb",
     "ruby-string-match-scorer.gemspec",
     "test/helper.rb",
     "test/test_ruby-string-match-scorer.rb"
  ]
  s.homepage = %q{http://github.com/bjeanes/ruby-string-match-scorer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Quicksilver-like string match scoring}
  s.test_files = [
    "test/test_ruby-string-match-scorer.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

